### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by tommykennedy** [joeherold/angular2-sails#10]
Hi Joe,

I am using systemjs to load the libraries. I had to add an entry for Typescript.js. I downloaded the package with NPM. However Typescript takes ages to load when the app first starts. Is there a better way to do this and is it needed?

```
  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    'angular2-sails':             'node_modules/angular2-sails',
    'typescript':                 'node_modules/typescript/lib/typescript.js',
  };
```

**Comment by ckszabi** [comment]
I am also looking for a proper usage with system.js.
Any hint is appreciated.

**Comment by joeherold** [comment]
I recommend using webpack... (easiest way with @angular/cli)

https://angular.io/docs/ts/latest/cli-quickstart.html
