### ISSUE TITLE
Failed at the angular2-sails@0.1.4 postinstall script 'typings install'.

### ISSUE THREAD

**Issue by lcborn4** [joeherold/angular2-sails#11]
when i run npm install --save angular2-sails

npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! angular2-sails@0.1.4 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-sails@0.1.4 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-sails package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-sails
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-sails
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Logan\Documents\Coding\SureCheck-SupportTools\npm-debug.log

**Comment by joeherold** [comment]
use version 0.2.8

**Comment by joeherold** [comment]
@lcborn4 
```node
npm install --save angular2-sails@latest
```
