### ISSUE TITLE
possible race condition

### ISSUE THREAD

**Issue by jseter** [joeherold/angular2-sails#12]
I notice in the get/post and other API calls that it wraps the callback and sends its result using an rxjs subject.  In this scenario the observable is hot so if there is sufficient (asynchronous) delay between returning  and the code subscribing that is longer than the time for the request to complete then the data might not be received by the caller (ie.  subject.next is called before there are any subscribers).   The most likely scenario would be if the data was passed to async pipe, in  which case there are a few tasks that may run before the change detection updates the transform pipe and the pipe subscribing.  It is hopefully slim given that a web server will take more time than a CPU but still exists.
Given the behavior of those particular calls it may make more sense to use a Promise or defer the socket call until subscribed.

**Comment by joeherold** [comment]
That's a good point!
I could change the subject to a behaviour subject.

**Comment by jseter** [comment]
Thanks.
Maintaining your function signature as observable I would think for get/post/... that  ReplaySubject might be better as it would play the same stream to each subscriber regardless of when they subscribe (being a stream of only a single item it should be cheap and Promise-like).
Another option, which would probably break some people using it is to use Observable.defer so it runs the action at the point you subscribe (but also each time you subscribe).

**Comment by joeherold** [comment]
this module is not longer maintained. we switched over to react and are not using angular any more.
