### ISSUE TITLE
TypeError: response.json is not a function

### ISSUE THREAD

**Issue by ChrisWorks** [joeherold/angular2-sails#14]
I am having a problem I am not able to figure out. 

When submitting a POST to /auth/local using the sails service I am getting an error when handling the response.

My code: 
```typescript
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import { Injectable, Inject } from '@angular/core';
import { Http, Headers, Response } from '@angular/http';
import { SailsService } from "angular2-sails";

@Injectable()
export class AuthenticationService {

    private url = '/auth/local';
    private explicitHost = 'localhost';
    private port = '1338';

    constructor(@Inject(SailsService) private _backend : SailsService, private http : Http) { this.init() }

    init() {
        console.log("AuthenticationService --> init");
	    this._backend.connect("http://" + this.explicitHost + ":" + this.port);
	}

    login(username: string, password: string) {
        
        return this._backend.post('/auth/local', { "identifier" : username, "password" : password })
            .map((response: Response) => {
                console.log("AuthenticationService --> login, success " + response);
                console.log(response);
                // login successful if there's a jwt token in the response
                let user = response.json();
                //let user = response;
                
                console.log("AuthenticationService --> login, user " + user);
                if (user && user.token) {
                    // store user details and jwt token in local storage to keep user logged in between page refreshes
                    localStorage.setItem('currentUser', JSON.stringify(user));
                }
            });
      }
    logout() {
        // remove user from local storage to log user out
        localStorage.removeItem('currentUser');
    }
}
```
However the response is an error:
**TypeError: response.json is not a function**

The login is successful and my response object is an object when I log it to the console:

Object {data: Object, statusCode: 200, response: JWR}
data:Object
response:JWR
statusCode:200
__proto__:Object

My package.json
```json
{
  "name": "frontend",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.config.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular2-sails": "^0.2.8",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "socket.io-client": "^1.7.3",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "angular-cli": "^1.0.0-beta.28.3",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"

```  }
}


Anyone have any ideas?

**Comment by joeherold** [comment]
the response body is in the data property. try to do:
```typescript
let user = response.data.json();
```

checkout this example:
https://joeherold.gitbooks.io/angular2-sails/content/examples.html

here the important info:
```typescript
/*
     * explanation of observable response object
     * 
     * resData = {
     *      data: <object>,
     *      statusCode: <number>,
     *      response: <jwres>,
     *      error: <undefined>
     * }
     * 
     * error = {
     *      data: null,
     *      statusCode: <number>,
     *      response: <jwres>,
     *      error: <jwres.error>
     * }
     */
```

**Comment by joeherold** [comment]
@ChrisWorks 
I edited your issue for syntax highlighting... ;)
is easier to read.

hope this resolves your issue. if so, please close it again.

yours, johannes

**Comment by ChrisWorks** [comment]
Hi Johannes, thank you for your response.

But when trying your suggestion I get a compilation error instead. I am using angular-cli and Visual Code:

`Failed to compile. Property 'data' does not exist on type 'Response'.`

**Comment by joeherold** [comment]
ah, I see. was too late yesterday...

you are mixing up things with the core http service.

when you use the
```typescript
http.get('someurl')
```
you will receive a Response object in the subscription/promise that has this special function to parse out the body of the http response.

the response object of this sails socket.io does not provide this kind of additional toolset.
in the data property of you response is, what you return in the action controller of your sails application. if it is a json or json array, this will be an object or array of objects in your response by default.

so you may use it that way:
```typescript
let user = response.data;
```

the response.json() of the http core service ist to interpret the body of a http request as json from a body with a json string.
no need to do that here.

**SIDENOTE**
a good habit is to create new objects instead of linking them. check out the manuals of redux or immutable.js

so one way would be to create a new object with object.assign
```typescript
let user = Object.assign({}, response.data);
```

I made a short video a while ago on how to use redux: https://youtu.be/yQXujtc_gI0

**Comment by joeherold** [comment]
to avoid ts error, use type of **any**
```typescript
.map((response: any) => {...
```

**OFF TOPIC**
one question: why do you use
```typescript
constructor(@Inject(SailsService) private _backend : SailsService, private http : Http)
````
instead of just 
```typescript
constructor(private _backend : SailsService, private http : Http)
```

**Comment by ChrisWorks** [comment]
Hi Johannes. Thanks for all your help. I got it working now; changing the type to **any** and using **response.data** (no .json()).

I am fairly new to the "let's do everything in JS" world (coming from enterprise Java), so I am still trying to get my head around concepts of promises, observables, etc. I have not looked at state containers (redux) yet (nor what I need them for).

RE **@Inject**. This was basically a leftover from when we were using the Angular2 RC versions. They had so many bugs and we had to add the **@Inject** to most constructor args to get stuff to work. Good to see things are improving.

**Comment by joeherold** [comment]
ah ok, I understand.

but in that case, you should think about developing your app with React and redux
much easier and faster development...

**Comment by ChrisWorks** [comment]
We are doing a multi-tenant quality management solution using Sails.js as backend and Angular.io as frontend.
I did look at React and also Ember, but I found that Reach was (for me atleast) very good for "read > write" applications where as ours is more a "write > read" application. What do you think?

**Comment by joeherold** [comment]
angular (formerly angular2)  is great, but in my opinion very slow during development process and getting into it.
and the other benefit is, that with redux, you can easily drop in an mobile application with react-native. there is an option for angular 2 as well, but not as good as react-native.

in general: it depends on the complexity of your application. angular is better for huge applications with a clear development plan.
react is better to get quick results ;)

**Comment by joeherold** [comment]
setting up an angular project by hand can drive you really nuts.
doing so with angular-cli, you will not exactly know whats going on.
and the worst thins is then, wenn it comes to an update of angular-cli and so...

but its up to you, what fits better.

for productive client applications, we avoided to use angular, just angularJS and react

**Comment by meena121rajesh** [comment]
Don't need to use this method -

.map((res: Response) => res.json() );
Just use this simple method instead of the previous method. hopefully you'll get your result:

.map(res => res );
