### ISSUE TITLE
SailsService throws - Cannot read property 'get' of undefined in angular-4

### ISSUE THREAD

**Issue by Rj-s** [joeherold/angular2-sails#15]
It has some issue with Angular-4    
package.json:- 
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",

I followed example.md file but facing error :-  Cannot read property 'get' of undefined(this._sailsService).

I would appreciate help.

Thanks

**Comment by joeherold** [comment]
how did you implement it?

**Comment by joeherold** [comment]
did you have a look at https://joeherold.gitbooks.io/angular2-sails/content/

**Comment by Rj-s** [comment]
Its my bad. I forgot to add  this._sailsService.connect('http://X.X.X.XX:1337') just before subscribing the observable.
I had to set io.socket.url also before connection to avoid errors in console. It was establishing localhost connection if we dont set it. 

    io.socket.url = 'http://X.X.X.XX:1337'; 
    this._sailsService.connect('http://X.X.X.XX:1337');

    // This is to fetch all values. 
    this._sailsService
      .get('/user')
      .subscribe(
      (resData) => {
        console.log(resData);
      },
      (error) => { console.log('Some error occured in socket-io', error); }
      );


    // This is to observe changed values from server side. 
    this._sailsService
      .on('user')
      .subscribe(
      (resData) => {
        console.log(resData);
      },
      (error) => { console.log('Some error occured in socket-io', error); }
      );

Thanks,

**Comment by joeherold** [comment]
fine. you are welcome
