### ISSUE TITLE
this._sailsService.on("event name") not fired in angular 4

### ISSUE THREAD

**Issue by satishverma143** [joeherold/angular2-sails#16]
Hey Team,
I am using this service.
and on button click i have call post request with this._sailsService.post and i had successfully applied.
but when i use this._sailsService.on in ngOnInit() then this is not fired in another end.
please help me how can i send data from sails server to client (angular 4) or how can i get the data from sails server to client.
* my client is built by angular 4 and back-end in sails 0.12.

please help me asap to resolve such issue.

**Comment by joeherold** [comment]
have you checked, that the sailsService is already connected in ngOnInit?

**Comment by joeherold** [comment]
post your code here

**Comment by satishverma143** [comment]
@joeherold yes i have checked it the service has connected in ngOnInit. but the service.on() method is not fired.
Please help me asap.

**Comment by joeherold** [comment]
If you want ASAP, than show your code. Otherwise it's not possible.

**Comment by joeherold** [comment]
How did you implement the entity listener?

**Comment by satishverma143** [comment]
@joeherold please see the above code i have mention both code client side & server sode.

constructor(private _sailsService:SailsService, private _userService:UserService) { }

ngOnInit(): void {
 let opts = {
         url: "http://localhost:1337",
         transports: ['polling', 'websocket'],
         headers: this._userService.socketHeaderToken(),
   }
   this._sailsService.connect(opts);

this._sailsService.on("user").subscribe(t => {
      console.log(t),
      error=>console.log(error)
    });

}
message(){
    this._sailsService.get('http://localhost:1337/hello', (data, jwRes)=>{
      console.log('Server responded with status code ' + jwRes + ' and data: ', data);
    });
  }

--------------------------------------And server side---------------------------------------
hello:function (req, res) {
        if (!req.isSocket) {
            return res.badRequest();
        }
	User.findOne({id: '59198b25fbf18ac732180657'}).exec(function(err, foundUser){
	      if (err) return res.serverError(err);
	     if (!foundUser) return res.notFound();
		
		console.log("foundUser : ",foundUser);
		//User.message(foundUser.id, {count: 12, hairColor: 'red'}); 
		console.log("req.socket.id : ",req.socket.id);
		sails.sockets.broadcast('message', 'user', { greeting: 'Hola!' }, req);
		return res.ok();
	});
}

----------------------------------------------------------
i have tried both model.message & broadcast:
but on client side nothing has happen.

**Comment by joeherold** [comment]
Before I get deeper into explanation of the sails framework. Please check of answer on listening to user model, when you mutate model records over a rest GUI like postman. But check auto pubsub is turned on ( by default on blueprint )

**Comment by joeherold** [comment]
So start your app, listen to user and then mutate user via postman

**Comment by joeherold** [comment]
And btw, get, post, .... is used with route, not with Uri. So /user instead of http://...

**Comment by satishverma143** [comment]
my server api hosted on other location and client on another location that's why i use http.

**Comment by satishverma143** [comment]
@joeherold when i use "this._sailsService.get" to get records, its work well but my problem is **broadcast a message and receive on client side** that's is build by angular 4.
my server api & front end client are hosted in different locations.
so please tell me what i do.

**Comment by joeherold** [comment]
You define API host in connect. No need to do so in get/post/put/delete

**Comment by joeherold** [comment]
If get works, so connection established, you do something wrong in your sails app. Is not related to angular2-sails

**Comment by joeherold** [comment]
Have you done, what I asked you to do? (Postman)

**Comment by joeherold** [comment]
Btw: I am not sure, if you understand the socket idea, if you use get with Uri.
You establish in connect a bidirectional socket connection. Angular2-sails is a wrapper for socket.io, not a common http Rest API...

**Comment by joeherold** [comment]
When you want to push a message from the server to a client, you have to fulfill some requirements to access the right socket connection, room and namespace 

That's why I ask you to check your subscription with postman

**Comment by joeherold** [comment]
BTW: in a controller action ( hello(req, res, next){} )
You do not emit to socket. You return a sails response

**Comment by joeherold** [comment]
Check out documentation for using sockets in sails:
http://sailsjs.com/documentation/reference/web-sockets

**Comment by satishverma143** [comment]
@joeherold how can i emit to socket in sails. can you give me some example?

**Comment by joeherold** [comment]
Please. Do what I asked you to. Subscribe for user and then mutate or add a dataset with a rest GUI client like Postman. 
Then you should see a response. If not, you messed up you sails config

**Comment by joeherold** [comment]
Sry man. But it's weekend now

**Comment by satishverma143** [comment]
@joeherold thanks for motivate me. i resolved the problem.

**Comment by joeherold** [comment]
@satishverma143 
try the following: 
```javascript
// server
// Be sure and check req.isSocket === true before passing in req
sails.sockets.blast(
   'myEvent', //event entity
   {myData: "data 1", alsoData: "data 2"}, //data to passs
   req // req object of your controller function
);


// client
this._sailsService
    .on('myEvent')
    .subscribe( response => {
          console.log("response", response);
     });
```
take a look here: https://github.com/joeherold/angular2-sails/blob/master/lib/sails.service.ts#L462

**Comment by joeherold** [comment]
@satishverma143 when you use ```sails.sockets.broadcast('message', 'user', { greeting: 'Hola!' }, req);```with **broadcast**, you should check, to what rooms your client has access ;)

check it out here: http://sailsjs.com/documentation/reference/web-sockets/sails-sockets/sails-sockets-rooms
