### ISSUE TITLE
"io is not defined" Despite including the socket.io library separately.

### ISSUE THREAD

**Issue by frostbytedata** [joeherold/angular2-sails#17]
Hi Joe,

First of all thank you for your work on this library. It is very helpful to those of us looking to use sails and angular. 

I am attempting to setup your library with Sails v1.0 and Ionic 2. I read the section in your readme about having to include the socket.io library along with the 'angular2-sails' library, as this does not include a version of it by default. I am positive I have properly included the socket.io-client library as instructed to me by the Ionic 2 team. Including it in Ionic is similar to including third party libraries with the Angular-CLI. (Ionic is a framework built on top of Angular). They both use webpack to compile the app. Here are the instructions I used to include socket.io-client and angular2.sails into my Ionic app: https://ionicframework.com/docs/resources/third-party-libs/ just for reference.

I have followed these steps, and also followed your readme on the setup in app.module.ts and usage in pages. I am certain I followed the instructions to the tee. I am running out of hope because after following all of these instructions as I still am receiving the "io is not defined" message in the console. 

Do you have any more suggestions on what I might be missing? Thanks so much. 

Parker

**Comment by joeherold** [comment]
Just add the socket.io.js from the angular project folder to your app. This should do the trick. Easiest add it to the head, than it is available in global scope of the window

**Comment by joeherold** [comment]
I meant socket.io.js from sails project.

**Comment by frostbytedata** [comment]
Thanks so much for your quick reply. I will try this out as soon as I'm home from work.

**Comment by frostbytedata** [comment]
@joeherold This advice has definitely cleared up the `io is not defined` message. Thanks so much! However, now I am seeing an error related to `sails.service.js`. It seems for some reason `this._io` is undefined. Here is a screenshot of the error and what my debugger shows on that line during runtime: 

http://i.imgur.com/CpWv31B.png

What might this be? Could it be a file loading order issue? Maybe SailsService is running before socket.io.js? Thanks again, do you accept tips through Paypal or Patreon?

**Comment by joeherold** [comment]
I yet haven't tried it with sails version 1.0, because this is still beta. maybe the io.sails.connect is not working any more in sails version 1.0. try the socket.io.js of a sails 0.12 application.

and thanks, but no tips needed. this is open source without billing money ;)

**Comment by joeherold** [comment]
@frostbytedata did this resolve your issue?

**Comment by frostbytedata** [comment]
Sorry for the delayed response. I haven't been able to try this out yet. I will try it as soon as I'm home from work. 

If it doesn't work, is there anyway I can help convert this library to work with sails v1? Thanks so much.

**Comment by joeherold** [comment]
don't worry, no stress

**Comment by frostbytedata** [comment]
https://github.com/balderdashy/sails-docs/blob/1.0/upgrading/To1.0.md#websockets

Looks like there may be some changes in the sails.io.js file. I will dig into this deeper later tonight and let you know if I find anything important.

**Comment by joeherold** [comment]
@frostbytedata  oh yes, there are really some minor changes. as I said, I yet haven't take a look at version 1.0, because it is still beta. but if you are willing to figure out the changes, this would be great!

**Comment by joeherold** [comment]
@frostbytedata ok, i will close this issue now, because of sails 1.0 beta and not stable 0.12.
