### ISSUE TITLE
Using Nginx reverse proxy returns 404 for the POST to socket.io, but the GET works.

### ISSUE THREAD

**Issue by ChrisWorks** [joeherold/angular2-sails#18]
Hi 

I am using the angular2-sails sailsService as a backend wrapper for my sails backend, and it has worked great when developing locally using angular-cli. I am not in the process on moving the code onto real servers, and I want to use Nginx to serve the Angular2 app.

So Sails is running on 1338 & Nginx is running on 9080 (testing purposes)

I have created an Nginx proxy config like this:

```
        location /socket.io/ {
            proxy_pass      http://127.0.0.1:1338/;
            proxy_redirect  http://127.0.0.1:1338/ /;
            proxy_read_timeout 60s;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";


            # May not need or want to set Host. Should default to the above hostname.
            proxy_set_header          Host            $host;
            proxy_set_header          X-Real-IP       $remote_addr;
            proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;

        }
```

When running the application I am seeing both HTTP 200s and 404s from the Socket.io calls in the browser:

<img width="792" alt="screenshot 2017-06-08 14 22 21" src="https://user-images.githubusercontent.com/4264444/26928298-ea24e968-4c55-11e7-8182-f47842d8abb3.png">
<img width="592" alt="screenshot 2017-06-08 14 22 07" src="https://user-images.githubusercontent.com/4264444/26928297-ea2263d2-4c55-11e7-9f30-8316d72d58da.png">

I looks like the sailsService (socket.io) is calling first using a HTTP GET, which returns a HTTP CODE 200 and then it does a HTTP POST, which returns a HTTP CODE 404, and then a GET, then POST, etc.

The Nginx access logs shows:

127.0.0.1 - - [07/Jun/2017:20:56:28 +0200] "GET /socket.io/?__sails_io_sdk_version=0.13.5&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=polling&t=Lo3waeP HTTP/1.1" **200** 21961 "http://localhost:8090/login?returnUrl=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "-"

127.0.0.1 - - [07/Jun/2017:20:56:29 +0200] "POST /socket.io/?__sails_io_sdk_version=0.13.5&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=polling&t=Lo3wafr HTTP/1.1" **404** 0 "http://localhost:8090/login?returnUrl=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "-"

When I am running using angular-cli (ng serve or npm start) everything works fine.

What could be the issue?

**Comment by joeherold** [comment]
I dont know, why you add an additional proxy for the socket.io path.

I use NginX config like that, for the whole sails application

```bash
server {
    listen 8080;
    
    server_name example.com;

    location / {
        proxy_pass http://10.0.1.127:1337;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP       $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

```

in your app, you define the host and port (in this case host ist example.com and port 8080) where the socket should connect to. and I do not add an proxy redirect....

you should be fine by passing the host and port in the connection options...
```typescript
...
ngOnInit() {
    this._sailsService.connect("http://yourDomain.com:9080");
    // or
    letl opts = {
        url: "http://yourDomain.com:9080",
        transports: ['polling', 'websocket'],
        headers: {...},
        ...
    }
    this._sailsService.connect(opts);
}
...
```

**Comment by joeherold** [comment]
If you are not passing a host and port, socket.io will connect to the location, where it was requested from.

so opening the app with http://yourdomain.com:9080 will connect to yourdomain:9080

**Comment by ChrisWorks** [comment]
Thanks for the reply, but your config will pass all request to Nginx to the backend, right? My Angular app is not served from Sails. I only use the Sails as a REST api. 

My Angular app is being served from Nginx.
```
    server {
        listen       8090;
        server_name  localhost;
        root /Users/xyz/Sites/dist;
        index index.html index.htm;

        location / {
            try_files $uri $uri/ =404;   
        }

        location /socket.io/ {
            proxy_pass      http://127.0.0.1:1338/;
            proxy_redirect  http://127.0.0.1:1338/ /;
            proxy_read_timeout 60s;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            # May not need or want to set Host. Should default to the above hostname.
            proxy_set_header          Host            $host;
            proxy_set_header          X-Real-IP       $remote_addr;
            proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
```

Basically I want my backend to respond to localhost:9080/api (seperate config) and localhost:9080/socket.io/ through the proxy config and all other urls including localhost:9080/index.html should be served from Nginx only.

**Comment by joeherold** [comment]
so your angular app is behind a proxy and your sails is behind a proxy.

so, than host sour sails under api.mydomain.com on port 80 and your app under whatever, www.mydomain.com or app.mydomain.com also on port 80.
in your nginx you set up 2 listeners on 2 domains/ports, one for sails, one for the app.
in your app you connect to api.mydomain.com:80 and you are fine to go

i will close this issue, because it is related to your NginX configuration and not to this ng2-module.

**Comment by ChrisWorks** [comment]
Hi Joe

Thanks for your reply. I am sorry for the misunderstanding, but my angular2 app is not behind a proxy. The Nginx is serving the Angular2 app using the static HTML built using "ng build" from the root /Users/xyz/Sites/dist folder.

I then want the Angular2 app to connect to the Sails backend using the same hostname:port/api, but the "/socket.io/" has to exist as well apparently.

If I follow your config the Nginx will only work as a reverse_proxy and cannot server the angular2 app from its static HTML files, correct? 

How do you serve your angular2 app?

**Comment by joeherold** [comment]
do not connect to the same host/port as your angular2 app is running on. connect to the host/port of your sails application

**Comment by joeherold** [comment]
i host them together in one application, so the built comes into the sails application. and then i connect to the public host

**Comment by ChrisWorks** [comment]
OK, we did that as well originally, but having the sails application serve the static html/javascript, that makes up the angular part of the app, seems like a bad idea. Why not use a web server for serving the static HTML/Javascript/CSS/images? That is what it is good at, right?

**Comment by joeherold** [comment]
sure, you are free to do it in any way. I dont say whats good an whats bad habit. you asked me how I serve an angular/sails app. thats what I do, because sails offers me the webserver right up anyway. in fact, sails is nothing else, than a web server process, just with less features. and behind a NginX, I can enable caching for the static stuff, what reduces payload on the sails application.

but feel totally free on how to achieve your solution. I heavily depends on your needs of your project.

so, splitting it apart, is a way to do so. when the sails service crashes (if not clustered) your frontend is useless anyway. the other way round depends on what you use of sails.

and when I cluster the sails app, including my frontend, my frontend is clustered also. so for me that way is less work to do.
