### ISSUE TITLE
Do you need help? I want to contribute to the project

### ISSUE THREAD

**Issue by adrianeguez** [joeherold/angular2-sails#19]

**Comment by joeherold** [comment]
@adrianeguez sure, you could figure out the changes for sails 1.0

**Comment by AndresFarias1110** [comment]
When installing angular2-sails in my project, it generates errors at the moment of executing
ng serves:
 The angular/compiler-cli package was not properly installed.
 Error: Error:
 Cannot find module angular/compiler-cl

**Comment by joeherold** [comment]
sorry, this module is not longer maintained. we switched over to react and are not using angular any more.
