### ISSUE TITLE
Error: NgFor only supports binding to Iterables such as Arrays

### ISSUE THREAD

**Issue by frehd-developer** [joeherold/angular2-sails#23]
I followed the instructions for the example with Async Pipe but i get that message when i run the application, i am using Angular 4 and Sails 0.12, also i get these messages while the application is running: GET XHR http://localhost:4200/socket.io/ [HTTP/1.1 404 Not Found 3ms]
Socket is trying to reconnect to Sails...
_-|>_-  (attempt #11)

**Comment by joeherold** [comment]
sorry, this module is not longer maintained. we switched over to react and are not using angular any more.
