### ISSUE TITLE
Can't disable autoconnect

### ISSUE THREAD

**Issue by agustinkassis** [joeherold/angular2-sails#24]
I've been trying for hours to disable the autoconnect.
I would like to use the service to connect to a different port, but there's simply no way to do it.

Using angular-cli, there's no way to set the autoConnect attribute.

**Comment by joeherold** [comment]
There are several ways do do so. 
Has nothing to do with angular cli. 
Check out the socket.io documentation. 

One way is e.g. adding your socket.io.js is a script tag and adding the data attribute data-auto-connect. 

See: https://socket.io/docs/client-api/

**Comment by joeherold** [comment]
Or modify your socket.io.js file you add to your application

**Comment by joeherold** [comment]
sorry, this module is not longer maintained. we switched over to react and are not using angular any more.
