### ISSUE TITLE
Running io.sails.connect outside angular zone

### ISSUE THREAD

**Issue by jwhollingsworth** [joeherold/angular2-sails#25]
Is there any technical reason why io.sails.connect() isn't wrapped to run outside the angular zone? Just wondering because the other io calls are wrapped, and to get my protractor tests -- for a hybrid AngularJS/Angular app I am currently upgrading -- to successfully run, I need to wrap the sailsService.connect() call to run outside the angular zone. Everything seems to work -- including the tests -- but wanted to make sure I wasn't missing anything.

Thanks for the great module.

Resolves this issue -- https://github.com/angular/angular/issues/11853

**Comment by joeherold** [comment]
Hey!

Feel free to fork this repo. Our team switched over to ReactJS
