### ISSUE TITLE
How to bind with on event

### ISSUE THREAD

**Issue by frazghuman** [joeherold/angular2-sails#27]
With the given example I am only able to get data once but by adding a new record it does not load.
Sails project is running on http://localhost:1337 and angular2+ cli project is running on http://localhost:4200
Thanks

**Comment by AtifJaved1** [comment]
@frazghuman, is this issue is resolved now? I am unable to bind the socket to "on" to the user model.

**Comment by joeherold** [comment]
sorry, this module is not longer maintained. we switched over to react and are not using angular any more.
