### ISSUE TITLE
Feature: Add new method to unsubscribe/delete registered observer

### ISSUE THREAD

**Issue by ysfdev** [joeherold/angular2-sails#28]
# Details
It will be great to have a public method which allows to explicitly unsubscribe an observer  that was initially subscribed with the specified `eventIdentity`. This will be useful, it cases when you know that they won't  be any new events triggered from the subscription, and you will like to dispose unused resources. 

# Example Usage
The new method may be implemented as follow:  
```js
this._sailsService.unsubscribe(<eventIdentity>);
```

I will be open to contribute integrating this feature!

Thanks!

**Comment by joeherold** [comment]
sorry, this module is not longer maintained. we switched over to react and are not using angular any more.
