### ISSUE TITLE
cannot use the on method

### ISSUE THREAD

**Issue by Hamashi** [joeherold/angular2-sails#29]
Hello, I would like to use sails.io.js with angular5, so I used angular2-sails module. I managed to connect angular to sails BUT I didn't manage to retrieve the events from sails.js, for example when a new document is created in database. Is there something to configure sails side ? I used `this.sailsService.on("user").subscribe(data => console.log("event on user"))`. The get and post methods are perfectly working. Sails side I put

```
ioclient:  require('socket.io-client')('http://localhost:1337'),
io: require('sails.io.js'),
```
In config/http.js, instead of 
`
var io = require('sails.io.js')( require('socket.io-client') );`

because sails cannot load else
I didn't write anything in config/socket.js

**Comment by joeherold** [comment]
sorry, this module is not longer maintained. we switched over to react and are not using angular any more.

**Comment by Hamashi** [comment]
Do you have any recommendation of module/technology to use for using sockets with angular5 + sailsJS ?
Thank you for your answer

**Comment by joeherold** [comment]
sails 0.12 or sails 1.0 ?

**Comment by Hamashi** [comment]
0.12

**Comment by joeherold** [comment]
ok, then work with the sails.io.js from sails itself directly. load it in your scope and grab it e.g. from global scope (window) and work with it.

**Comment by Hamashi** [comment]
Do you have an example project ? Thank you for your help
