### ISSUE TITLE
return statuscode

### ISSUE THREAD

**Issue by Anuovec** [joeherold/angular2-sails#3]
Why don't you return at least the statuscode with the data?

**Comment by joeherold** [comment]
I return the data only to be used with async pipe directly.
in case of no success (2**), it will target the reactive error subscription

**Comment by joeherold** [comment]
everything under 200 or over 400 ist targeted to the error

``` typescript
request(options:any):Observable<any> {
        let subject = new Subject();

        this.zone.runOutsideAngular(()=> {

            this._io.request(options, (resData, jwres:IJWRes) => {

                if (io.sails.environment != "production") {
                    console.log("request::data", resData)
                    console.log("request:jwr", jwres)
                }
                if (jwres.statusCode < 200 || jwres.statusCode >= 400) {
                    subject.error(jwres.error)
                } else {
                    this.zone.run(() => subject.next(resData));
                }
                subject.complete();
            })
        })
        return subject.asObservable();
    }
```

**Comment by Anuovec** [comment]
Yes, I can see that, but usually you need to know the exact statucode to determine what another action is going to be. To know, if it is error or not is not enough.

**Comment by joeherold** [comment]
I could easily change it to return an response object, but first I would have to update our PUB-SUB library... :(

**Comment by joeherold** [comment]
I will change this:

``` typescript
this.zone.run(() => subject.next(resData));
```

to that:

``` typescript
this.zone.run(() => subject.next({
    response: jwres,
    data: resData
}));
```

jwres has the following structure:

``` typescript
interface IJWRes {
    body:any;
    error?:any;
    headers:any;
    statusCode:number
}
```

will this be fine to you?

**Comment by Anuovec** [comment]
Yes, tha would be great. Also, you should do this in the case of error.

**Comment by Anuovec** [comment]
_How are you progressing with the change?_

**Comment by joeherold** [comment]
not really, had birthday party that weekend...

**Comment by joeherold** [comment]
done...

**Comment by joeherold** [comment]
@Anuovec sorry, took a while, too much other things to do...
