### ISSUE TITLE
disconnect must clear this._pubsubSubscriptions

### ISSUE THREAD

**Issue by danil-z** [joeherold/angular2-sails#30]
If you call _sailsService.disconnect() method  and then connect again,
on subscription subject stored no longer valid and never fire!
you have to clean this._pubsubSubscriptions  property in disconnect method

**Comment by danil-z** [comment]
they don't work because after new connection you try to bind events again but they exist in your mapping  (but referred to old io socket instance...:

    SailsService.prototype.on = function (eventIdentity) {
        var _this = this;
        var self = this;
        if (!this._pubsubSubscriptions[eventIdentity] || this._pubsubSubscriptions[eventIdentity].isComplete) {

**Comment by joeherold** [comment]
this repo is no longer maintained
