### ISSUE TITLE
ON not working

### ISSUE THREAD

**Issue by certifirm** [joeherold/angular2-sails#32]
Hi.  I don't know if is an issue, but I follow your manual and the "on" trigger doesn't work.   All the other methods works perfectly, like get, post, put, ...  but on it's necessary for realtime communication.

Have you an example how to use it?

In this link talks about your library is "deprecated".  Is it right? 

https://stackoverflow.com/questions/48094972/using-angular2-sails-module-for-realtime-communication-using-sockets

Thanks a lot.

**Comment by joeherold** [comment]
yes, this project is no longer maintained

**Comment by certifirm** [comment]
Could put it in the README?  
May be important thing...
Thanks a lot

**Comment by joeherold** [comment]
mentioned in readme

**Comment by joeherold** [comment]
Now also mentioned in NPMjs: [https://www.npmjs.com/package/angular2-sails](https://www.npmjs.com/package/angular2-sails)

**Comment by certifirm** [comment]
Thanks for your work.
For another users that arrives here:
https://github.com/burntblark/ngx-sails-socketio/
