### ISSUE TITLE
Working with Systemjs

### ISSUE THREAD

**Issue by tommykennedy** [joeherold/angular2-sails#5]
Hi Joe,

I am trying to get this working with systemjs. Do you have any example of the entry needed to support this?

I have the following entry but I'm not sure its complete or correct. 

  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'angular2-sails':             'node_modules/angular2-sails/lib',
  };

Tom

**Comment by tommykennedy** [comment]
I was able to to get it working with he following entries

  ```
var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    'angular2-sails':             'node_modules/angular2-sails',
    'typescript':                 'node_modules/typescript/lib/typescript.js'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'angular2-sails':             { main: 'index.js'},
  };
```

I also had to install typescript with 

npm install typescript

Is this the correct approach using systemjs?

**Comment by lcborn4** [comment]
whenever i add 

'angular2-sails':             { main: 'index.js'},

to the var packages, i get a 
GET http://localhost:1337/traceur 404 (Not Found)

**Comment by lcborn4** [comment]
When i remove 

'angular2-sails': { main: 'index.js'}, 

from packages

I get this error
zone.js:1382 GET http://localhost:1337/node_modules/angular2-sails/ 404 (Not Found)

Please help

**Comment by joeherold** [comment]
for systemjs use version 0.1.3

https://github.com/joeherold/angular2-sails/tree/0.1.3

**Comment by joeherold** [comment]
nothing more? than I will close this issue

**Comment by ckszabi** [comment]
version 0.1.3 is not available anymore on npm :(

**Comment by joeherold** [comment]
switched module packaging in version v0.2.8 to commonjs instead of es6.
