### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by lcborn4** [joeherold/angular2-sails#6]
I am getting a 

GET http://localhost:1337/angular2-sails 404 (Not Found)

**Comment by joeherold** [comment]
do you use it with systemjs or webpack? current version is ment for webpack. for systemjs use version 0.1.3

**Comment by lcborn4** [comment]
im using version 0.1.4 however, im having an issue with app.module.ts

do i still need to import SailsModule? if so, what file is it from? 
import {SailsModule} from "angular2-sails"; is not working like in version 0.2.1

Thanks,

**Comment by joeherold** [comment]
ah, yes... damn. 0.2.x is ready for the ngModule, 0.1.x not...
is your project on github? if so, invite me and I will have a look

**Comment by lcborn4** [comment]
i have it working, i just commented out the module. version 0.1.4 must have just the service. it works fine now

**Comment by joeherold** [comment]
great
