### ISSUE TITLE
sailsService.connect(opts) throwing a error

### ISSUE THREAD

**Issue by zoharsherman** [joeherold/angular2-sails#9]
when using:
let opts = {
      url: SERVER_URL,
      headers: {'Authorization':'JWT '+this.jwtToken},
    }
    this.sailsService.connect(opts);

i am getting:
EXCEPTION: Error in :0:0 caused by: undefined is not an object (evaluating 'this._serverUrl.length')

when i use:
this.sailsService.connect(SERVER_URL, opts);

the opts are totally ignored.
see sails.service.ts line:93 is commented out
     // this._opts = opts || {}

**Comment by farahty** [comment]
i have same issue

**Comment by joeherold** [comment]
I will fix it today and push it

**Comment by joeherold** [comment]
https://github.com/joeherold/angular2-sails/commit/5688c7400dc570a9bd6fb1b929492622922647bc
